// Downloads the game's Google Fonts as local woff2 files + public/assets/fonts/fonts.css (bundled, so the game
// needs no font CDN at runtime: LAN play without internet works, and nothing pops in late).
//   node scripts/tools/fonts.mjs
import fs from 'node:fs';
import path from 'node:path';

const OUT = 'public/assets/fonts';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';
// [css2 query, local family name]
const FAMILIES = [
  ['family=Barlow+Condensed:ital,wght@0,600;0,700;0,800;1,700;1,800', 'Barlow Condensed'],
  ['family=Kaushan+Script', 'Kaushan Script'],
  [`family=Dela+Gothic+One&text=${encodeURIComponent('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 !?.,:;-+/%&()\'"')}`, 'Dela Gothic One'],
  // Japanese signage on the map (only these characters: the subset is a few KB)
  [`family=Yuji+Syuku&text=${encodeURIComponent('ラーメン一楽木ノ葉忍者茶屋団子本屋武器薬宿里の火影慰霊碑演習場')}`, 'Yuji Syuku'],
];

fs.mkdirSync(OUT, { recursive: true });
let css = '/* generated by scripts/tools/fonts.mjs */\n';
let n = 0;
for (const [q, fam] of FAMILIES) {
  const r = await fetch(`https://fonts.googleapis.com/css2?${q}&display=block`, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${fam}: ${r.status}`);
  let text = await r.text();
  // keep the latin subsets for latin families (the file lists cyrillic, vietnamese... too)
  const blocks = text.split('@font-face').slice(1).map((b) => '@font-face' + b.slice(0, b.indexOf('}') + 1));
  const prev = text.split('@font-face');
  for (let i = 0; i < blocks.length; i++) {
    // each face is preceded by its subset name: /* latin */, /* cyrillic */, or /* [42] */ for CJK chunks
    const comment = (prev[i].match(/\/\* ([^*]+?) \*\/\s*$/) || [])[1] || '';
    if (fam !== 'Yuji Syuku' && comment && comment !== 'latin') continue;
    let b = blocks[i];
    const url = b.match(/url\((https:[^)]+)\)/)[1];
    const style = (b.match(/font-style: (\w+)/) || [])[1] || 'normal';
    const weight = (b.match(/font-weight: (\d+)/) || [])[1] || '400';
    const file = `${fam.replace(/\s+/g, '')}-${weight}${style === 'italic' ? 'i' : ''}${comment && comment !== 'latin' ? '-' + comment : ''}.woff2`;
    const data = Buffer.from(await (await fetch(url)).arrayBuffer());
    fs.writeFileSync(path.join(OUT, file), data);
    b = b.replace(/url\(https:[^)]+\)/, `url(/assets/fonts/${file})`);
    css += b + '\n';
    n++;
    console.log(`  ${file} ${(data.length / 1024).toFixed(0)} KB`);
  }
}
fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
console.log(`wrote ${OUT}/fonts.css (${n} faces)`);
